FROM golang:alpine as builder

WORKDIR /go/src/app
ENV GO111MODULE=on
# golang设置国内代理
ENV GOPROXY=https://goproxy.cn,direct
RUN go install github.com/cespare/reflex@latest

COPY go.mod .
COPY go.sum .

RUN go mod download
COPY . .

RUN go build .

# subcontainer for running environment

FROM alpine:latest
WORKDIR /root
COPY --from=builder /go/src/app/OpenDictionary .
EXPOSE 8080
CMD [ "./OpenDictionary" ]